### ISSUE TITLE
Rate-limit service must be include in the policies bundle

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/jenkins-scripts#12]
Rate-limit is splitted into two components:
* policy
* service

Currently, only the policy is part of the policies bundle. But the service is also required at runtime by the gateway.

**Comment by NicolasGeraud** [comment]
should i add services into policies bundle or may i have to provide a services bundle ?

**Comment by brasseld** [comment]
You have to include it in the policies bundle.
