### ISSUE TITLE
Create repository with all mandatory files and configuration

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/jenkins-scripts#4]
When we add a new repo, we must : 
*  add CONTRIBUTING.adoc
*  add README.adoc
*  update github issues labels
*  add .editorconfig
*  optionnaly update release.json
*  create the jenkins build job
*  add .gitignore
*  add LICENSE.txt
*  protect master branch
*  add repository into Waffle.io

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/ichiou#41
